컬럼보기

RowNumber:행번호
CustomerId:고객 ID 
Surname : 성(이름의 성)
CreditScore : 신용점수
Geography : 고객이 살고 있는 국가
Gender : 성별
Age : 나이
Tenure : 은행에 있었던 년수 
Balance : 계좌에 있는 돈의 양
NumOfProducts : 은행에서 사용하는 상품의 수
HasCrCard : 신용카드 유무 
IsActiveMember : 고객 활성화 유무 1은 미활성, 0은 활성하게 사용중이라는 것 
EstimatedSalary : 예상급여
Exited :은행사용 유무, 1은 은행을 떠났다는 것 0은 아직 은행을 이용하고 있다는 것
    
6개월간 관찰해서 만든 데이터셋

In [ ]:
# https://www.udemy.com/course/linear-regression-with-artificial-neural-network/learn/lecture/18888982#overview

# Artificial Neural Network

### Importing the libraries

In [372]:
import numpy as np
import pandas as pd
import tensorflow as tf
#import matplotlib.pyplot as plt

In [373]:
tf.__version__

'2.5.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [374]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values #array로 변환
                                #행번호, 고객ID열, 이름의 성은 은행 사용 유무에 영향을 미치지 않으므로 제거  
y = dataset.iloc[:, -1].values #array로 변환

In [375]:
dataset.head(25)

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0           1    15634602   Hargrave          619    France  Female   42   
1           2    15647311       Hill          608     Spain  Female   41   
2           3    15619304       Onio          502    France  Female   42   
3           4    15701354       Boni          699    France  Female   39   
4           5    15737888   Mitchell          850     Spain  Female   43   
5           6    15574012        Chu          645     Spain    Male   44   
6           7    15592531   Bartlett          822    France    Male   50   
7           8    15656148     Obinna          376   Germany  Female   29   
8           9    15792365         He          501    France    Male   44   
9          10    15592389         H?          684    France    Male   27   
10         11    15767821     Bearce          528    France    Male   31   
11         12    15737173    Andrews          497     Spain    Male   24   
12         13    15632264        Kay          476    France  Female   34   
13         14    15691483       Chin          549    France  Female   25   
14         15    15600882      Scott          635     Spain  Female   35   
15         16    15643966    Goforth          616   Germany    Male   45   
16         17    15737452      Romeo          653   Germany    Male   58   
17         18    15788218  Henderson          549     Spain  Female   24   
18         19    15661507    Muldrow          587     Spain    Male   45   
19         20    15568982        Hao          726    France  Female   24   
20         21    15577657   McDonald          732    France    Male   41   
21         22    15597945   Dellucci          636     Spain  Female   32   
22         23    15699309  Gerasimov          510     Spain  Female   38   
23         24    15725737     Mosman          669    France    Male   46   
24         25    15625047        Yen          846    France  Female   38   

    Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0        2       0.00              1          1               1   
1        1   83807.86              1          0               1   
2        8  159660.80              3          1               0   
3        1       0.00              2          0               0   
4        2  125510.82              1          1               1   
5        8  113755.78              2          1               0   
6        7       0.00              2          1               1   
7        4  115046.74              4          1               0   
8        4  142051.07              2          0               1   
9        2  134603.88              1          1               1   
10       6  102016.72              2          0               0   
11       3       0.00              2          1               0   
12      10       0.00              2          1               0   
13       5       0.00              2          0               0   
14       7       0.00              2          1               1   
15       3  143129.41              2          0               1   
16       1  132602.88              1          1               0   
17       9       0.00              2          1               1   
18       6       0.00              1          0               0   
19       6       0.00              2          1               1   
20       8       0.00              2          1               1   
21       8       0.00              2          1               0   
22       4       0.00              1          1               0   
23       3       0.00              2          0               1   
24       5       0.00              1          1               1   

    EstimatedSalary  Exited  
0         101348.88       1  
1         112542.58       0  
2         113931.57       1  
3          93826.63       0  
4          79084.10       0  
5         149756.71       1  
6          10062.80       0  
7         119346.88       1  
8          749

In [376]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [377]:
print(dataset.iloc[:, -1].shape, y) #일차원 array로 만들어줌

(10000,) [1 0 1 ... 1 1 0]


In [378]:
#결측치 확인
dataset.isna().sum()
#결측치 없음

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [379]:
x[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

### Encoding categorical data

Label Encoding the "Gender" column

In [380]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
x[:,2] = le.fit_transform(x[:,2]) #여자0 남자1

In [381]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [272]:
"""
# ColumnTransformer 예시

# ColumnTranformer 로 열 변환자 객체 정의 
preprocessor = ColumnTransformer(transformers=[
                                               ('numeric', num_pipe_line, num_x_training),
                                               ('categoryical', cat_pipe_line, cat_x_training)
"""

"\n# ColumnTransformer 예시\n\n# ColumnTranformer 로 열 변환자 객체 정의 \npreprocessor = ColumnTransformer(transformers=[\n                                               ('numeric', num_pipe_line, num_x_training),\n                                               ('categoryical', cat_pipe_line, cat_x_training)\n"

In [382]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
#                                                                    열
#passthrouth 옵션 :변환기에 지정되지 않은 나머지 모든 열은 자동으로 전달됨
x = np.array(ct.fit_transform(x))

In [383]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [275]:
###########################번외#############################

In [158]:
#dummy를 활용한 방법으로 ohe hot encoding
pd.get_dummies(dataset['Geography'])

France  Germany  Spain
0          1        0      0
1          0        0      1
2          1        0      0
3          1        0      0
4          0        0      1
...      ...      ...    ...
9995       1        0      0
9996       1        0      0
9997       1        0      0
9998       0        1      0
9999       1        0      0

[10000 rows x 3 columns]

In [186]:
#One Hot Encoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False) #True로 설정하면 희소 행렬을 반환하고 그렇지 않으면 배열을 반환
                                   #False로 사용할 것
tx=ohe.fit_transform(dataset[['Geography']])
#tx

#sklearn.preprocessing.OneHotEncoder를 사용하여 변환된 결과는 numpy.array이기 때문에 이를 데이터프레임으로 변환하는 과정이 필요
pd.DataFrame(tx, columns=['France', 'Germany', '.Spain'])

France  Germany  .Spain
0        1.0      0.0     0.0
1        0.0      0.0     1.0
2        1.0      0.0     0.0
3        1.0      0.0     0.0
4        0.0      0.0     1.0
...      ...      ...     ...
9995     1.0      0.0     0.0
9996     1.0      0.0     0.0
9997     1.0      0.0     0.0
9998     0.0      1.0     0.0
9999     1.0      0.0     0.0

[10000 rows x 3 columns]

### Splitting the dataset into the Training set and Test set

In [384]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

### Feature Scaling

In [385]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
#x 기준(학습데이터 기준)
x_train = ss.fit_transform(x_train)
x_test = ss.fit_transform(x_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [386]:
ann = tf.keras.models.Sequential()
ann

### Adding the input layer and the first hidden layer

In [387]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #무작위로 시작, 활성함수

### Adding the second hidden layer

In [388]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [389]:
#은행을 이용할 것인지 이용하지 않을 것인지 0과 1로 구분해서 분류하므로 unit은 1로 지정
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) #결과가 1일 확률 산출

## Part 3 - Training the ANN

### Compiling the ANN

In [390]:
ann.compile(optimizer= 'adam' , loss= 'binary_crossentropy', metrics= ['accuracy'])
#                      최적화,  손실함수, 평가를 위해 여러 매트릭스를 선택할 수 있음. 반드시 []안에 넣어야 함
#활성함수가 softmax일 경우: categorical_corssentropy

### Training the ANN on the Training set

In [391]:
ann.fit(x_train, y_train, batch_size=32, epochs = 100) #보통 32
#accuracy:0.8625 

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5778 - accuracy: 0.7291
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4727 - accuracy: 0.7980
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4475 - accuracy: 0.7993
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4327 - accuracy: 0.8049
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4224 - accuracy: 0.8085
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4123 - accuracy: 0.8124
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4008 - accuracy: 0.8141
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3903 - accuracy: 0.8173
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3814 - accuracy: 0.8215
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3739 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3322 - accuracy: 0.8627
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3323 - accuracy: 0.8643
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3323 - accuracy: 0.8636
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8643
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3323 - accuracy: 0.8636
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3323 - accuracy: 0.8636
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3326 - accuracy: 0.8627
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3324 - accuracy: 0.8635
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3324 - accuracy: 0.8639
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3320 - accuracy: 

## Part 4 - Making the predictions and evaluating the model

In [363]:
#개인

t_data = pd.DataFrame({'Geography':['France'], 'CraditScore':[600], 'Gender':['Male'],
                      'Age':[40], 'Tenure':[3], 'Balance':[60000], 'NumOfProducts':[2],
                      'HasCrCard':[1], 'IsActiveMember':[1], 'EstimatedSalary':[50000]})
t_data

Geography  CraditScore Gender  Age  Tenure  Balance  NumOfProducts  \
0    France          600   Male   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [ ]:
#ohe 이슈
"""
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
#                                                                    열
#passthrouth 옵션 :변환기에 지정되지 않은 나머지 모든 열은 자동으로 전달됨
x = np.array(ct.fit_transform(x))

위에서 이런 과정을 거쳤는데 열이 달라져서 사용할 수 없음
"""

In [364]:
#le
t_data['Gender']=le.transform(t_data['Gender'])
###ohe 
tt_data=pd.DataFrame(ohe.transform(t_data[['Geography']]), columns=['France', 'Germany', 'Spain']) #[[]] 처리 안하면 에러

#total
test_sample=pd.concat([tt_data, t_data], axis=1).drop(columns='Geography')
test_sample

France  Germany  Spain  CraditScore  Gender  Age  Tenure  Balance  \
0     1.0      0.0    0.0          600       1   40       3    60000   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0              2          1               1            50000

In [393]:
#df 
print(ann.predict(ss.transform(test_sample)))
#np.array
print(ann.predict(ss.transform(np.array(test_sample))))
#df나 [[]]형식으로 넣어야 함
ann.predict(ss.transform(test_sample))>0.5

[[0.02117845]]
[[0.02117845]]


C:\Users\admin\anaconda3\envs\yolo\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
C:\Users\admin\anaconda3\envs\yolo\lib\site-packages\sklearn\base.py:444: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


array([[False]])

In [392]:
#풀이

#인공신경망을 스케일링 된 값으로 훈련시켰기 때문에 반드시 test set도 스케일링 해야함
#[[]]형태로 넣어야 함
print(ann.predict(ss.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
ann.predict(ss.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) >0.5
# 이 고객이 은행을 떠날 것으로 예상되는 확률 반환
# 근데 마지막에 0.5 임계값을 두고 최종적으로 확인
# False로 은행을 떠나지 않을 것이라는 것을 확인

[[0.02117845]]


array([[False]])

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [413]:
y_test, 'to', y_test.reshape(len(y_test),1)

(array([0, 1, 0, ..., 0, 0, 0], dtype=int64),
 'to',
 array([[0],
        [1],
        [0],
        ...,
        [0],
        [0],
        [0]], dtype=int64))

In [414]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
##                                                   [[]] array형태로 변환  
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
#concatenate는 선택한 축 방향으로 배열을 연결해줌

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
"""
#1차원
[1,2,3], [4,5,6]    >>> [1,2,3,4,5,6]

#2차원 axis=0
[[1,2], [10,20]], [[3,4], [30, 40]] >> [[1,2], [10,20], [3,4], [30,40]]

#2차원 axis=1
[[1,2], [10,20]], [[3,4], [30, 40]] >> [[1,2,3,4], [10,20,30,40]]

"""

### Making the Confusion Matrix

In [416]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
# 63명은 남아있지만 떠나는 것으로 잘못 예측
# 206명은 떠나지만 남아있는 것으로 잘못 예측

[[1532   63]
 [ 206  199]]


0.8655