In [2]:
#2강
#테스트 검증 셋은 한번만 돌림
#테스트 데이터셋은 모델의 성능이 어느정도 나왔을때 "최종적"으로 측정함.

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

#data:input data(feature)
#target:output data(label)
iris_data = load_iris()
                                                 # input        , output          , test셋 비율 (기본값0.25)        #원본의 라벨값 주기   
X_train, X_test,y_train, y_test= train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=12, stratify=iris_data.target)
print(X_train.shape, X_test.shape,y_train.shape, y_test.shape)
print(np.unique(iris_data.target, return_counts=True))
print(np.unique(iris_data.target, return_counts=True))
#원본 데이터의 각 class 들의 비율과 동일하게 나눔.(분류문제일 때 설정)

#모델 생성
dt_clf = DecisionTreeClassifier()
#모델 학습 -fit(featuren, label)
dt_clf.fit(X_train, y_train)
#추론(예측) - predict(예측대상 feature): 예측결과
pred = dt_clf.predict(X_test)
#accuracy_score(정답, 예측): 평가결과, 정확도
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

(105, 4) (45, 4) (105,) (45,)
(array([0, 1, 2]), array([50, 50, 50], dtype=int64))
(array([0, 1, 2]), array([50, 50, 50], dtype=int64))
예측 정확도: 0.9778


In [3]:
iris_data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [18]:
#홀드아웃
#다양한 패턴을 가진 데이터가 많을 때 사용
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

#train/test 분리 > 전체에서 test set 분리
X_train, X_test,y_train, y_test= train_test_split(iris_data.data, iris_data.target, 
                                                    test_size=0.2, random_state=0, stratify=iris_data.target)
#train>train/validation 셋으로  
X_train, X_validation, y_train, y_validation = train_test_split(X_train, y_train, test_size=0.2, random_state=0, stratify=y_train)

print(X_train.shape, X_validation.shape, X_test.shape)

#모델생성                      하이퍼파라미터                       
dt_clf = DecisionTreeClassifier(max_depth=1)
#학습
dt_clf.fit(X_train, y_train)
#추론> validation set으로 
val_pred = dt_clf.predict(X_validation)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_validation, val_pred)))

(96, 4) (24, 4) (30, 4)
예측 정확도: 0.6667


In [19]:
#최종평가 > test set 마지막 한번
test_pred = dt_clf.predict(X_test)
accuracy_score(y_test, test_pred)

0.6666666666666666

In [ ]:
#cross validation 
"""
KFold
-회귀문제의 Dataset을 분리할 때 사용
-Raw dataset의 순서를 유지하면서 지정한 개수로 분할한다.
-iris_data.target을 보면 범주형은 k-fold를 사용하지 않는지 즉,
 왜 순서를 유지한 채로 분할하면 안되는지 알 수 있음
 분할한 구역에 특정 범주만 존재할 수도 있기 때문

StratifiedKFold
-분류분제의 Dataset을 분리할 때 사용
-
"""

In [5]:
#k-fold cross validation
#데이터 양이 적을 때
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X,y = load_iris(return_X_y=True) #data(feature), target(label)만 반환

#KFold객체 생성 > 데이터셋을 3분할
kfold = KFold(n_splits=3)

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:
l=[1,2,3,4,5]
it=iter(l)
print(next(it))
print(next(it))
print(next(it))
next(it)

1
2
3


4

In [33]:
ex = kfold.split(X)
print(type(ex))
next(ex) #튜플(train data index 배열, test data index 배열)로 반환

<class 'generator'>


(array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
         76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
        115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
        128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143, 144, 145, 146, 147, 148, 149]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]))

In [34]:
next(ex)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
        115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
        128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143, 144, 145, 146, 147, 148, 149]),
 array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]))

In [35]:
next(ex)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]))

In [39]:
#여러건의 평가결과들을 저장할 리스트
acc_train_list = [] #train set 정확도들
acc_test_list = [] #test set 정확도들

for train_index, test_index in kfold.split(X):
    #데이터 분리 -generator가 반환한 index를 이용해 데이터 추출(조회)
    X_train, y_train = X[train_index], y[train_index]
    X_test, y_test = X[test_index], y[test_index]
    
    # 모델생성
    tree = DecisionTreeClassifier()
    
    # 학습
    tree.fit(X_train, y_train)
    
    # 검증
    pred_train = tree.predict(X_train)
    pred_test = tree.predict(X_test)
    
    # 평가 - 정확도 
    acc_train = accuracy_score(y_train, pred_train)
    acc_test = accuracy_score(y_test, pred_test)
    #평가결과를 리스트에 추가
    acc_train_list.append(acc_train)
    acc_test_list.append(acc_test)

In [40]:
acc_train_list, np.mean(acc_train_list)

([1.0, 1.0, 1.0], 1.0)

In [41]:
#분류문제에서 kfold 를 사용하면 안되는 이유
#각 데이터셋에는 특정 범주가 포함되지 않을 수도 있음
#현재 데이터셋의 경우 iris 3종 50개씩 잘라서 데이터셋 하나당 한 종류에 대해 학습이 불가
acc_test_list, np.mean(acc_test_list) 

([0.0, 0.0, 0.0], 0.0)

In [ ]:
#stratifiedKfold
#나뉜 fold 들에 label들이 같은(또는 거의 같은) 비율로 구성 되도록 나눈다.
#랜덤으로 가지고 오는건 아니고 순서대로 같은 비율의 범주들을 가져옴

In [43]:
from sklearn.model_selection import StratifiedKFold

s_fold = StratifiedKFold(n_splits=3)
acc_train_list = []
acc_test_list = []

In [44]:
ex= s_fold.split(X,y)

In [45]:
next(ex)

(array([ 17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
         30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
        128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143, 144, 145, 146, 147, 148, 149]),
 array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  50,  51,  52,  53,  54,  55,  56,  57,  58,
         59,  60,  61,  62,  63,  64,  65,  66, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]))

In [46]:
#비율에 맞춰야 하므로 X,y값을 제공

for train_index, test_index in s_fold.split(X, y):
    #index를 이용해서 train/test set 조회
    X_train, y_train = X[train_index], y[train_index]
    X_test, y_test = X[test_index], y[test_index]
    
    # 모델생성
    tree = DecisionTreeClassifier()
    
    # 학습
    tree.fit(X_train, y_train)
    
    # 예측
    pred_train = tree.predict(X_train)
    pred_test = tree.predict(X_test)
    
    # 평가
    acc_train = accuracy_score(y_train, pred_train)
    acc_test = accuracy_score(y_test, pred_test)
    
    acc_train_list.append(acc_train)
    acc_test_list.append(acc_test)


In [47]:
acc_train_list, np.mean(acc_train_list)

([1.0, 1.0, 1.0], 1.0)

In [48]:
acc_test_list, np.mean(acc_test_list)

([0.98, 0.92, 0.98], 0.96)

In [ ]:
#cross val score
#데이터셋을 K개로 나누고 K번 반복하면서 평가하는 작업을 처리해 주는 함수
"""
주요매개변수
estimator: 학습할 평가모델객체
X: feature
y: label
scoring: 평가지표
cv: 나눌 개수 (K)
반환값: array - 각 반복마다의 평가점수
"""

In [49]:
from sklearn.tree import DecisionTreeClassifier
#cross_validate는 평가지표 여러개 볼때
#sross_val_score는 평가지표 하나만 볼 수 있음
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris
import numpy as np

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 평가결과 배열 = cross_val_score(모델, X, y, scoring평가지표, cv=k겹의 개수)
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:',np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667
