In [1]:
#7장 영상분할

In [2]:
"""
컨투어 : 영상에서 같은 색상이나 밝기의 연속된 점을 찾아 잇는 곡선을 찾아내면
모양 분석과 객체인식에 사용할 수 있는데, 이것을 컨투어라고 함.

dst, contours, hierarchy = cv2.findCountours(src, mode, method [, contours, hierarchy, offset])
  - src : 입력 이미지, 바이너리 스케일, 검은색 배경 흰색 전경
  - mode : 컨투어 제공방식 선택
    -cv2.RETR_EXTERNAL:가장 바깥쪽 라인만 제공
    -cv2.RETR_LIST:모든 라인을 계층 없이 제공
    -cv2.RETR_CCOMP: 모든 라인을 2계층으로 제공
    -cv2.RETR_TREE:모든 라인의 모든 계층 정보를 트리구조로 제공
  -method: 근사값 방식 선택
    -cv2.CHAIN_APPROX_NONE: 근사 계산하지 않고 모든 좌표 제공
    -cv2.CHAIN_APPROX_SIMPLE: 컨투어 꼭짓점 좌표만 제공
    -cv2.CHAIN_APPROX_TC89_L1: Teh-Chin 알고리즘으로 좌표 개수 축소
    -cv2.CHAIN_APPROX_APPROX_TCOS: Teh-Chin 알고리즘으로 좌표 개수 축소
  -contours: 검출한 컨투어 좌표, 파이썬 리스트
  -hierarchy:컨투어 계층 정보
    -Next, Prev, FirstChild, Parent
    - -1: 해당사항 없음
  -offset:ROI등으로 인해 이동한 컨투어 좌표의 오프셋

cv2.drawContours(img, contours, contourIdx, color, thickness)
  -img:입력영상
  -contours:그림 그릴 컨투어 베열
  -contourIdx:그림 그릴 컨투어 인덱스, -1:모든 컨투어 표시
  -colors:색상값
  -thickness:선두께, 0:채우기
"""

"""
설명
"""

'\n설명\n'

In [14]:
#원래 교재 코드 근데 실패함 img2 배제해야 함

#컨투어 찾기와 그리기
import cv2
import numpy as np

img = cv2.imread('./img/shapes.png')
img2 = img.copy()

#그레이 스케일로 변환
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#스레시홀드로 바이너리 이미지로 만들어서 검은색 배경에 흰색 전경으로 반전
ret, imthres = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)

#가장 바깥쪽 컨투어에 대해 모든 좌표 반환
img2, contour, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

#가장 바깥쪽 컨투어에 대해 모든 좌표 반환
img2, contour2, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

#각 컨투어의 개수 출력
print('도형의 갯수: , %d(%d) '% (len(contour), len(contour2)))

#모든 좌표를 값는 컨투어 그리기, 초록색
cv2.drawContours(img, contour, -1, (0,255,0), 4)
#꼭짓점 좌표만을 갖는 컨투어 그리기, 초록색
cv2.drawContours(img2, contour2, -1, (0,255,0), 4)

#컨투어의 모든 좌표를 작은 파란색 점(원)으로 표시
for i in contour:
    for j in i:
        cv2.circle(img, tuple(j[0]), 1, (255,0,0), -1)

#컨투어의 꼭짓점 좌표를 작은 파란색 점(원)으로 표시
for i in contour2:
    for j in i:
        cv2.circle(img2, tuple(j[0]), 1, (255,0,0), -1)


#결과출력
cv2.imshow('CHAIN_APPROX_NONE', img)
cv2.inshow('CHAIN_APPROX_SIMPLE', img2)
cv2.waitkey()
cv2.destroyAllWindows()

ValueError: not enough values to unpack (expected 3, got 2)

In [17]:
#컨투어 찾기와 그리기
import cv2
import numpy as np

img = cv2.imread('./img/shapes.png')
img2 = img.copy()

#그레이 스케일로 변환
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#스레시홀드로 바이너리 이미지로 만들어서 검은색 배경에 흰색 전경으로 반전
ret, imthres = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)

#가장 바깥쪽 컨투어에 대해 모든 좌표 반환
contour, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

#가장 바깥쪽 컨투어에 대해 모든 좌표 반환
contour2, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

#각 컨투어의 개수 출력
print('도형의 갯수: %d(%d) '% (len(contour), len(contour2)))

#모든 좌표를 값는 컨투어 그리기, 초록색
cv2.drawContours(img, contour, -1, (0,255,0), 4)
#꼭짓점 좌표만을 갖는 컨투어 그리기, 초록색
cv2.drawContours(img2, contour2, -1, (0,255,0), 4)

#컨투어의 모든 좌표를 작은 파란색 점(원)으로 표시
for i in contour:
    for j in i:
        cv2.circle(img, tuple(j[0]), 1, (255,0,0), -1)

#컨투어의 꼭짓점 좌표를 작은 파란색 점(원)으로 표시
for i in contour2:
    for j in i:
        cv2.circle(img2, tuple(j[0]), 1, (255,0,0), -1)


#결과출력
cv2.imshow('CHAIN_APPROX_NONE', img)
cv2.imshow('CHAIN_APPROX_SIMPLE', img2)
cv2.waitKey()
cv2.destroyAllWindows()

도형의 갯수: 3(3) 


In [12]:
#원래 교재 코드 근데 실패함 img2 배제해야 함
#컨투어 계층 트리
import cv2
import numpy as np

img = cv2.imread('./img/shapes_donut.png')
img2 = img.copy()

#바이너리 이미지로 변환
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#스레시홀드로 바이너리 이미지로 만들어서 검은색 배경에 흰색 전경으로 반전
ret, imthres = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)

#가장 바깥쪽 컨투어만 수집
img2, contour, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

#컨투어 개수와 계층 트리 출력
print(len(contour), hierarchy)

#모든 컨투어를 트리계층으로 수집
im2, contour2, hierarchy = cv2.findContours(imthres, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

#컨투어 개수와 계층 트리 출력
print(len(contour2), hierarchy)

#가장 바깥 컨투어만 그리기
cv2.drawContours(img, contour, -1, (0,255,0), 3)

#모든 컨투어 그리기
for idx, cont in enumerate(contour2):
    #랜덤한 컬러 추출
    color = [int(i) for i in np.random.randint(0,255,3)]
    #컨투어 인덱스마다 랜덤한 색상으로 그리기
    cv2.drawContours(img2, contour2, idx, color, 3)
    #컨투어 첫 좌표에 인덱스 숫자 표시
    cv2.putText(img2, str(idx), tuple(cont[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (0,0,255))
    
#화면 출력
cv2.imshow('RETR_EXTERNAL', img)
cv2.imshow('RETR_TREE', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

ValueError: not enough values to unpack (expected 3, got 2)

In [ ]:
#컨투어 계층 트리
import cv2
import numpy as np

img = cv2.imread('./img/shapes_donut.png')
img2 = img.copy()

#바이너리 이미지로 변환
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#스레시홀드로 바이너리 이미지로 만들어서 검은색 배경에 흰색 전경으로 반전
ret, imthres = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)

#가장 바깥쪽 컨투어만 수집
contour, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

#컨투어 개수와 계층 트리 출력
print(len(contour), hierarchy)

#모든 컨투어를 트리계층으로 수집
contour2, hierarchy = cv2.findContours(imthres, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

#컨투어 개수와 계층 트리 출력
print(len(contour2), hierarchy)

#가장 바깥 컨투어만 그리기
cv2.drawContours(img, contour, -1, (0,255,0), 3)

#모든 컨투어 그리기
for idx, cont in enumerate(contour2):
    #랜덤한 컬러 추출
    color = [int(i) for i in np.random.randint(0,255,3)]
    #컨투어 인덱스마다 랜덤한 색상으로 그리기
    cv2.drawContours(img2, contour2, idx, color, 3)
    #컨투어 첫 좌표에 인덱스 숫자 표시
    cv2.putText(img2, str(idx), tuple(cont[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (0,0,255))
    
#화면 출력
cv2.imshow('RETR_EXTERNAL', img)
cv2.imshow('RETR_TREE', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

#이상

In [2]:
#이미지 모멘트와 컨투어 속성
"""
모멘트는 물리학에서 힘의 양을 기술할 때 사용하는 용어인데,
영상에서도 대상 물체의 양적인 속성을 표현할 때 모멘트라는 용어 사용

0-3차수 모멘트는 공간 모멘트라고 하며, 위치나 크기가 달라지면 그 값도 달라짐.
위치가 변해도 값이 동일한 모멘트를 중심모멘트라고 함.
"""
"""
cv2.moments(contour)
  -contour:모멘트 계산 대상 컨투어 좌표
  -moment:결과 모멘트 ,파이썬 딕셔너리
    -m00, m01, m10, m11, m02, m12, m20, m21, m03, m30,: 공간 모멘트
    -mu20, mu11, mu02, mu30, mu21, mu12, mu03:중심 모멘트
    -nu20, nu11, nu02, nu30, nu21, nu03:정규화 중심 모멘트
"""

"""
cv2.contourArea(contour[, oriented=False]):컨투어로 넓이 계산
  -contour:넓이를 계산할 컨투어
  -oriented:컨투어 방향 플래그
    -True:컨투어 방향에 따라 음수 반환
    -False:절대값 반환
  -retval:컨투어 영역의 넓이 값

cv2.arcLength(curve, closed): 컨투어로 둘레의 길이 계산
curve:둘레 길이를 계산할 컨투어
closed:닫힌 호인지 여부 플래그
retval:컨투어의 둘레길이 값
"""
print('')

In [ ]:
#모멘트를 이용한 중심점, 넓이, 둘레길이
import cv2
import numpy as np

img = cv2.imread('./img/shapes.png')
#그레이 스케일 변환
imgray =cv2.cvtColor(img, cv2.COLOR_BG2GRAY)
#바이너리 스케일 변환
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
#컨투어 찾기
img2, contours, hierachy = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

#각 도형의 컨투어에 대한 루프
for c in contours:
    #모멘트 계산
    mmt = cv2.moments(c)
    #m10/m00, m01/m00 중심점 계산
    cx = int(mmt['m10']/mmt['m00'])
    cy = int(mmt['m01']/mmt['m00'])
    #영역넓이
    a=mmt['m00']
    #영역 외곽선 길이
    l = cv2.arcLength(c, True)
    #중심점에 노란색 점 그리기
    cv2.circle(img, (cx,cy), 5, (0,255,255),-1)
    #중심점 근처에 넓이 그리기
    cv2.putText(img, "A:%.0f"%a, (cx, cy+20), cv2.FONT_HERSHEY_PLAIN, 1, (0,0,255))
    #컨투어 시작점에 길이 그리기
    cv2.putText(img, "L:%.2f"%l, tuple(c[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (255,0,0))
    #함수로 컨투어 넓이 계산해서 출력
    print('area:%.2f'%cv2.contourArea(c,False))
    
#결과출력
cv2.imshow('center', img)
cv2.waitKey()
cv2.destroyAllWindows()
    

In [5]:
#원본 이상
#모멘트를 이용한 중심점, 넓이, 둘레길이
import cv2
import numpy as np

img = cv2.imread('./img/shapes.png')
#그레이 스케일 변환
imgray =cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#바이너리 스케일 변환
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
#컨투어 찾기
contours, hierachy = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

#각 도형의 컨투어에 대한 루프
for c in contours:
    #모멘트 계산
    mmt = cv2.moments(c)
    #m10/m00, m01/m00 중심점 계산
    cx = int(mmt['m10']/mmt['m00'])
    cy = int(mmt['m01']/mmt['m00'])
    #영역넓이
    a=mmt['m00']
    #영역 외곽선 길이
    l = cv2.arcLength(c, True)
    #중심점에 노란색 점 그리기
    cv2.circle(img, (cx,cy), 5, (0,255,255),-1)
    #중심점 근처에 넓이 그리기
    cv2.putText(img, "A:%.0f"%a, (cx, cy+20), cv2.FONT_HERSHEY_PLAIN, 1, (0,0,255))
    #컨투어 시작점에 길이 그리기
    cv2.putText(img, "L:%.2f"%l, tuple(c[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (255,0,0))
    #함수로 컨투어 넓이 계산해서 출력
    print('area:%.2f'%cv2.contourArea(c,False))
    
#결과출력
cv2.imshow('center', img)
cv2.waitKey()
cv2.destroyAllWindows()
    

area:9870.00
area:12544.00
area:6216.00


In [6]:
"""
cv2.boundingRect(contour): 좌표를 감싸는 사각형 구하기
  - x,y : 사각형 왼쪽 상단 좌표
  - w,h : 폭, 높이
  
cv2.minAreaRect(contour):좌표를 감싸는 최소한의 사각형 계산
  - rotateRect : 회전한
"""

In [9]:
#원본 안됨
#컨투어를 감싸는 도형 그리기
import cv2
import numpy as np

#이미지를 읽어서 그레이 스케일 변환, 바이너리 스케일 변환
img = cv2.imread('./img/lightning.png')
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)

#컨투어 찾기
im, contours, hr = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contr = contours[0]

#감싸는 사각형 표시(검은색)
x,y,w.h = cv2.boundingRect(contr)
cv2.rectangle(img, (x,y), (x+w, y+h), (0,0,0), 3)

#최소한의 사각형 표시(초록색)
rect = cv2.minAreaRect(contr)
box = cv2.boxPoints(rect) #중심점과 각도를 4개의 꼭짓점 좌표로 변환
box = np.int0(box) #정수로 변환
cv2.drawContours(img, [box], -1, (0,255,0), 3)

#최소한의 원 표시(파란색)
(x,y), radius = cv2.minEnclosingCircle(contr)
cv2.circle(img, (int(x), int(y)), int(radius), (255,0,0), 2)

#최소한의 삼각형 표시(분홍색)
ret, tri = cv2.minEnclosingTriangle(contr)
cv2.polylines(img, [np.int32(tri)], True, (255,0,255), 2)

#최소한의 타원 표시(노란색)
ellipse = cv2.fitEllipse(contr)
cv2.ellipse(img, ellipse, (0,255,255), 3)

#중심점을 통과하는 직선 표시(빨간색)
[vx, vy, x, y] = cv2.fitLine(contr, cv2.DIST_L2,0,0.01,0.01)
cols, rows = img.shape[:2]
cv2.line(img, (0, 0-x*(vy/vx) +y), (cols-1, (cols-x)*(vy/vx) +y), (0,0,255), 2)

#결과출력
cv2.imshow('Bound Fit shapes', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


ValueError: not enough values to unpack (expected 3, got 2)

In [17]:
#원본 안됨
#컨투어를 감싸는 도형 그리기
import cv2
import numpy as np

#이미지를 읽어서 그레이 스케일 변환, 바이너리 스케일 변환
img = cv2.imread('./img/lightning.png')
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)

#컨투어 찾기
contours, hr = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contr = contours[0]

#감싸는 사각형 표시(검은색)
x,y,w,h = cv2.boundingRect(contr)
cv2.rectangle(img, (x,y), (x+w, y+h), (0,0,0), 3)

#최소한의 사각형 표시(초록색)
rect = cv2.minAreaRect(contr)
box = cv2.boxPoints(rect) #중심점과 각도를 4개의 꼭짓점 좌표로 변환
box = np.int0(box) #정수로 변환
cv2.drawContours(img, [box], -1, (0,255,0), 3)

#최소한의 원 표시(파란색)
(x,y), radius = cv2.minEnclosingCircle(contr)
cv2.circle(img, (int(x), int(y)), int(radius), (255,0,0), 2)

#최소한의 삼각형 표시(분홍색)
ret, tri = cv2.minEnclosingTriangle(contr)
cv2.polylines(img, [np.int32(tri)], True, (255,0,255), 2)

#최소한의 타원 표시(노란색)
ellipse = cv2.fitEllipse(contr)
cv2.ellipse(img, ellipse, (0,255,255), 3)

#중심점을 통과하는 직선 표시(빨간색)
[vx, vy, x, y] = cv2.fitLine(contr, cv2.DIST_L2,0,0.01,0.01)
cols, rows = img.shape[:2]
cv2.line(img, (0, int(0-x*(vy/vx)+y)), (cols-1, int((cols-x)*(vy/vx) + y)), (0, 0, 255), 2)

#결과출력
cv2.imshow('Bound Fit shapes', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [1]:
#컨투어의 단순화
"""
실생활에서 얻는 영상은 대부분 물체가 정확히 표현되는 경우보다는 
노이즈와 침식이 일어나는 경우가 더 많음. 그래서 컨투어도 정확한 컨투어보다는
오히려 부정확하게 단순화한 컨투어가 쓸도가 있는 경우가 더 많음
"""
#epsilon은 오차범위

'\n실생활에서 얻는 영상은 대부분 물체가 정확히 표현되는 경우보다는 \n노이즈와 침식이 일어나는 경우가 더 많음. 그래서 컨투어도 정확한 컨투어보다는\n오히려 부정확하게 단순화한 컨투어가 쓸도가 있는 경우가 더 많음\n'

In [2]:
"""
cv2.approxPolyDP(contour, epsilon, closed)
  - contour:대상 컨투어 좌표
  - epsilon:근사값 정확도, 오차범위
  - closed:컨투어의 닫힘 여부
  - approx:근사 계산한 컨투어 좌표
"""

'\ncv2.approxPolyDP(contour, epsilon, closed)\n  - contour:대상 컨투어 좌표\n  - epsilon:근사값 정확도, 오차범위\n  - closed:컨투어의 닫힘 여부\n  - approx:근사 계산한 컨투어 좌표\n'

In [1]:
#근사 컨투어
import cv2
import numpy as np

img =cv2.imread('./img/bad_rect.png')
img2 = img.copy()

#그레이 스케일과 바이너리 스케일 변환
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) 
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY)
 
#컨투어 찾기
contours, hierachy = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contour = contours[0]

print('contour', contour)

#전체 둘레의 0.05로 오차범위 지정
epsilon = 0.05 * cv2.arcLength(contour, True)
#근사 컨투어 계산
approx = cv2.approxPolyDP(contour, epsilon, True)

#각각 컨투어 선 그리기
cv2.drawContours(img, [contour], -1, (0,255,0), 3)
cv2.drawContours(img2, [approx], -1, (0,255,0), 3)

#결과출력
cv2.imshow('contour', img)
cv2.imshow('approx', img2)
cv2.waitKey()
cv2.destroyAllWindows()

contour [[[287   7]]

 [[286   8]]

 [[286  10]]

 [[285  11]]

 [[285  12]]

 [[284  13]]

 [[284  15]]

 [[283  16]]

 [[283  17]]

 [[282  18]]

 [[282  20]]

 [[281  21]]

 [[281  22]]

 [[280  23]]

 [[280  25]]

 [[279  26]]

 [[244  26]]

 [[242  28]]

 [[242  29]]

 [[239  32]]

 [[239  33]]

 [[237  35]]

 [[237  36]]

 [[235  38]]

 [[235  39]]

 [[232  42]]

 [[232  43]]

 [[230  45]]

 [[230  46]]

 [[227  49]]

 [[227  50]]

 [[225  52]]

 [[225  53]]

 [[223  55]]

 [[223  56]]

 [[220  59]]

 [[220  60]]

 [[217  63]]

 [[215  61]]

 [[214  61]]

 [[212  59]]

 [[212  58]]

 [[213  57]]

 [[213  56]]

 [[215  54]]

 [[215  53]]

 [[218  50]]

 [[218  49]]

 [[220  47]]

 [[220  46]]

 [[222  44]]

 [[222  43]]

 [[225  40]]

 [[225  39]]

 [[227  37]]

 [[227  36]]

 [[229  34]]

 [[229  33]]

 [[232  30]]

 [[232  29]]

 [[234  27]]

 [[234  26]]

 [[171  26]]

 [[170  25]]

 [[170  12]]

 [[164  12]]

 [[164  25]]

 [[163  26]]

 [[109  26]]

 [[110  27]]

 [[110  28]]

In [3]:
#컨투어를 단순화하는 또다른 방법(볼록선체)
#결함은 오목한 부분을 의미
"""
볼록선체: 어느 한 부분도 오목하지 않은 상태를 말하는 것으로 대상 객체를 완전히 
          포함하므로 객체의 외곽 영역을 찾는데 좋음. 
          
cv2.convexHull(points [, hull, colckwise, returnPoints]):볼록 선체찾기
  - points: 입력 컨투어
  - hull : 볼록 선체 결과
  - clockwise:방향지정(True는 시계방향)
  - returnPoints: 결과 좌표 형식 선택
    - True: 볼록선체 좌표 반환
    - False:입력 컨투어 중에 볼록 선체에 해당하는 인덱스 반환
  -cv2.isContourConvex(contour):볼록 선체 만족 여부 확인
    - retval: True인 경우 볼록 선체 만족
  -defects:cv2.convexityDefects(contour, convexhull):볼록 선체 결함 찾기
    -contour:입력 컨투어
    -convexhull:볼록 선체에 해당하는 컨투어의 인덱스
    -defects:볼록 선체 결함이 있는 컨투어의 배열 인덱스, N x 1 x 4배열
  -[start, end, farthest, distance]
    -start:오목한 각이 시작되는 컨투어의 인덱스
    -end:오목한 각이 끝나는 컨투어의 인덱스
    -farthest:볼록 선체에서 가장 먼 오목한 지점의 컨투어 인덱스
    -distance:farthest와 볼록 선체와의 거리, 8비트 고정 소수점(distance/256.0)
"""
print('')

In [7]:
#볼록선체
import cv2
import numpy as np

img = cv2.imread('./img/hand.jpg')
img2 = img.copy()

#그레이 스케일 및 바이너리 스케일 변환
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, th = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY_INV)

#컨투어 찾기와 그리기
contours, heiarchy = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

cntr = contours[0]
cv2.drawContours(img, [cntr], -1, (0,255,0), 1)

#볼록 선체 찾기(좌표기준)와 그리기
hull = cv2.convexHull(cntr)
cv2.drawContours(img2, [hull], -1, (0,255,0), 1)

#볼록 선체 만족 여부확인
print(cv2.isContourConvex(cntr), cv2.isContourConvex(hull))

#볼록 선체 찾기(인덱스 기준)
hull2 = cv2.convexHull(cntr, returnPoints=False)

#볼록선체 결함찾기
defects = cv2.convexityDefects(cntr, hull2)

#볼록 선체 결함 순회
for i in range(defects.shape[0]):
    #시작, 종료, 가장먼 지점, 거리
    startP, endP, farthestP, distance = defects[i, 0]
    #가장 먼 지점의 좌표 구하기
    farthest = tuple(cntr[farthestP][0])
    #거리를 부동 소수점으로 변환
    dist = distance/256.0
    #거리가 1보다 큰 경우
    if dist >1:
        #빨간점 표시
        cv2.circle(img2, farthest, 3, (0,0,255), -1)
#결과 이미지 표시
cv2.imshow('contour', img)
cv2.imshow('convex hull', img2)
cv2.waitKey()
cv2.destroyAllWindows()

False True


In [8]:
#컨투어와 도형매칭
"""
서로다른 물체의 컨투어를 비교하면 두 물체가 얼마나 비슷한 모양인지 알아낼 수 있음

cv2.matchShapes(contour1, contour2, method, parameter):두 개의 컨투어로 도형 매칭
  - contour1, contour2:비교할 2개의 컨투어
  - method:휴 모멘트 비교 알고리즘 선택 플래그
    -cv2.CONTOURS_MATCH_T1
    -cv2.CONTOURS_MATCH_T2
    -cv2.CONTOURS_MATCH_T3
  - parameter:알고리즘에 전달을 위한 예비인수, 현재 지원안됨(0으로 고정)
  -retval:닮음정도, 0=동일, 클수록 다름
  
cv2.matchShapes()함수는 2개의 컨투어를 인자로 받아서 휴 모멘트 비교 알고리즘에 따라 
비교한 결과를 소수점 있는 숫자로 반환
"""
print('')

In [11]:
#도형 매칭으로 비슷한 도형 찾기
import cv2
import numpy as np

#매칭을 위한 이미지 읽기
target = cv2.imread('./img/4star.jpg') #매칭 대상
shapes = cv2.imread('./img/shapestomatch.jpg') #여러도형
#그레이 스케일 변환
targetGray = cv2.cvtColor(target, cv2.COLOR_BGR2GRAY)
shapesGray = cv2.cvtColor(shapes, cv2.COLOR_BGR2GRAY)

#바이너리 스케일 변환
ret,targetTH = cv2.threshold(targetGray, 127, 255, cv2.THRESH_BINARY_INV)
ret,shapesTH = cv2.threshold(shapesGray, 127, 255, cv2.THRESH_BINARY_INV)

#컨투어 찾기
cntrs_target, _ =cv2.findContours(targetTH, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cntrs_shapes, _ =cv2.findContours(shapesTH, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

#각 도형과 매칭을 위한 반복문
matchs = [ ] #컨투어와 매칭 점수를 보관할 리스트
for contr in cntrs_shapes:
    #대상 도형과 여러 도형중 하나와 매칭 실행
    match= cv2.matchShapes(cntrs_target[0], contr, cv2.CONTOURS_MATCH_I2, 0.0)
    #해당 도형의 매칭 점수와 컨투어를 쌍으로 저장
    matchs.append((match, contr))
    #해당 도형의 컨투어 시작 지점에 매칭 점수 표시
    cv2.putText(shapes, '%.2f'%match, tuple(contr[0][0]),
               cv2.FONT_HERSHEY_PLAIN, 1, (0,0,255), 1)
#매칭 점수로 정렬
matchs.sort(key=lambda x: x[0])
#가장 적은 매칭 점수를 얻는 도형의 컨투어에 선 그리기
cv2.drawContours(shapes, [matchs[0][1]], -1, (0,255,0), 3)
cv2.imshow('target', target)
cv2.imshow('match shape', shapes)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
#허프 변환
"""
각 점마다 여러개의 가상의 선을 그어서 그 선들 중 평면 원점과 직각을 이루는 
선을 찾아 각도와 거리를 구해서 모든 점에게 동일하게 나타나는 선이 있다면, 
그 점들은 그 선을 따라 직선의 형태를 띄는 것이라고 볼 수 있음.

cv2.HoughLines(img, rho, theta, threshold[, lines, srn=0, stn=0, min_theta, max_theta])
  - img:입력 영상, 1채널 바이너리 스케일
  - rho:거리 측정 해상도, 0-1
  - theta:각도 측정 해상도, 라디안 단위(np.pi/0~180)
  - threshold:직선으로 판단할 최소한의 동일 개수
    - 작은 값:정확도 감소, 검출 개수 증가
    - 큰값:정확도 증가, 검출 개수 감소
  -lines:검출 결과, N x 1 x 2 배열(r.theta)
  -srn, stn: 멀티 스케일 허프 변환에 사용, 선 검출에서는 사용 안함.
  -min_theta, max_theta:검출을 위해 사용할 최대, 최소 각도
"""         
print('')

In [15]:
#허프 선 검출
import cv2
import numpy as np

img = cv2.imread('./img/sudoku.jpg')
img2 = img.copy()
h, w = img.shape[:2]

#그레이 스케일 변환 및 엣지 검출
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(imgray, 100, 200)
#허프 선 검출
lines = cv2.HoughLines(edges, 1, np.pi/180, 130)
for line in lines: #검출된 모든 선 순회
    r, theta = line[0] #거리와 각도
    tx, ty = np.cos(theta), np.sin(theta) #x,y 축에 대한 삼각비
    x0, y0 = tx*r, ty*r #x,y기준(절편)좌표
    #기준 좌표에 빨간색 점 그리기
    cv2.circle(img2, (abs(x0), abs(y0)), 3, (0,0,255), -1)
    #직선 방정식으로 그리기 위한 시작점, 끝점 계산
    x1, y1 = int(x0 + w*(-ty)), int(y0 + h *tx)
    x2, y2 = int(x0 - w*(-ty)), int(y0 - h *tx)
    #선 그리기
    cv2.line(img2, (x1,y1),(x2, y2), (0,255,0), 1)
    
#결과 출력
merged = np.hstack((img, img2))
cv2.imshow('hough line', merged)
cv2.waitKey()
cv2.destroyAllWindows()

error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'circle'
> Overload resolution failed:
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type


In [16]:
import cv2
import numpy as np

img = cv2.imread('./img/sudoku.jpg')
img2 = img.copy()
h, w = img.shape[:2]
# 그레이 스케일 변환 및 엣지 검출 ---①
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(imgray, 100, 200 )
# 허프 선 검출 ---②
lines = cv2.HoughLines(edges, 1, np.pi/180, 130)
for line in lines: # 검출된 모든 선 순회
    r,theta = line[0] # 거리와 각도wh
    tx, ty = np.cos(theta), np.sin(theta) # x, y축에 대한 삼각비
    x0, y0 = tx*r, ty*r  #x, y 기준(절편) 좌표
    # 기준 좌표에 빨강색 점 그리기
    cv2.circle(img2, (abs(x0), abs(y0)), 3, (0,0,255), -1)
    # 직선 방정식으로 그리기 위한 시작점, 끝점 계산
    x1, y1 = int(x0 + w*(-ty)), int(y0 + h * tx)
    x2, y2 = int(x0 - w*(-ty)), int(y0 - h * tx)
    # 선그리기
    cv2.line(img2, (x1, y1), (x2, y2), (0,255,0), 1)

#결과 출력    
merged = np.hstack((img, img2))
cv2.imshow('hough line', merged)
cv2.waitKey()
cv2.destroyAllWindows()

error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'circle'
> Overload resolution failed:
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type


In [ ]:
#확률적 허프 선 변환
"""
허프 선 검출으 모든 점에 대해 수많은 선을 그어서 직선을 찾기 때문에 
무척 많은 연산 필요 이것을 개선한 것이 점진적 확률 허프 변환
이것은 모든 점을 고려하지 않고 무작위로 선정한 픽셀로 허프변환을 수행해 
점점 그 수를 증가시켜 가는 방법
"""        

In [17]:
"""cv2.HoughLinesP(img, rho, theta, threshold[, lines, minLineLength, maxLineGap])
  - minLineLength:선으로 인정할 최소 길이
  - maxLineGap:선으로 판단한 최대간격
  - lines:검출된 선 좌표, N x 1 x 4 배열(x1, y1, x2, y2)
  - 이외의 인자는 cv2.HoughLines와 동일"""
print('')

In [22]:
#확률 허프 변환으로 선 검출
import cv2
import numpy as np

img = cv2.imread('./img/sudoku.jpg')
img2 = img.copy()


#그레이 스케일 변환 및 엣지 검출
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(imgray, 50, 200)

#확률 허프 변환 적용
lines = cv2.HoughLinesP(edges, 1, np.pi/180, 10, None, 20, 2)
for line in lines: 
    #검출된 선 그리기
    x1, y1, x2, y2 = line[0]
    cv2.line(img, (x1, y1), (x2,y2), (0,255,0), 1)

merged = np.hstack((img2, img))
cv2.imshow('probability hough line', merged)    

cv2.waitKey()
cv2.destroyAllWindows()


In [ ]:
#허프 원 변환
"""
직교좌표를 극좌표로 바꾸면 (x,y)whkvyfmf (r,theta)좌표로 변환할 수 있으므로 
허프직선 변환의 알고리즘을 그대로 적용해서 원을 구할 수 있음.
"""

In [ ]:
"""
#케니 엣지는 그냥 내장되어 있음

cv2.Houghcircles(img, method, dp, minDist[, circles, param1, param2, minRadius, maxRadius])
  - img : 입력영상, 1채널 배열
  - method:검출 방식 선택, 현재 cv2.HOUGH_GRANTINT만 가능
    -cv2.HOUGH_STANDATD
    -cv2.HOUCH_PROBABILISTIC
    -cv2.HOUGH_MULTI_SCALE
    -cv2.HOUGH_GRANDIENT
  -dp:입력 영상과 경사 누적의 해상도 반비례율, 1:입력과 동일, 값이 커질수록 부정확
  -minDist:원들 중심 간의 최소 거리, 0:dpfj(동심원 검출 불가)
  -circles:검출 원 결과, N x 1 x 3 부동 소수점 배열(x,y,반지름)
  -param1:캐니엣지에 전달할 스레시홀드 최대 값(최소값은 최대값의 2배 작은값을 전달)
  -param2:경사도 누적 경계 값(값이 작을 수록 잘못된 원 검출)
  -minRadius, MaxRadius:원의 최소 반지름, 최대 반지름(0이면 영상의 크기)
"""

In [1]:
#허프 원 검출
import cv2
import numpy as np

img = cv2.imread('./img/coins_connected.jpg')
#그레이 스케일 변환
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#노이즈 제거를 위한 가우시안 블러
blur = cv2.GaussianBlur(gray, (3,3), 0)
#허프 원 변환 적용(dp=1.5, minDist=30, cany_max=200)
circles = cv2.HoughCircles(blur, cv2.HOUGH_GRADIENT, 1.3, 30, None, 200) #원본 1.5
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0,:]:
        #원 둘레에 초록색 원 그리기
        cv2.circle(img,(i[0], i[1]), i[2], (0, 255, 0), 2)
        #원 중심점에 빨간색 원 그리기
        cv2.circle(img, (i[0], i[1]), 2, (0,0,255), 5)
        
#결과출력
cv2.imshow('hough circle', img)
cv2.waitKey()
cv2.destroyAllWindows()
    

In [ ]:
#연속영역분할

In [ ]:
#거리변환
"""
영상에서 물체의 영역을 정확히 파악하기 위한 방법으로 물체의 최중심점을 찾는 것이 중요한데
그것을 사람이나 동물로 비유하면 뼈대와 같은 것르로 흔히 스켈레톤이라 함.
스켈레톤을 검출하는 방법 중 하나가 주변 경계로부터 가장 멀리 떨어진 곳을 찾는 거리 변환

거리변환: 바이너리 스케일 이미지를 대상으로 원본이미지와 같은 크기의 배열에 
          픽셀값이 0인 위치에 0으로 시작해서 멀어질 때마다 1씩 증가하는 방식으로
          경계로부터 갖아 먼 픽셀이 가장 큰 값을 갖게 하는 변환
"""

In [ ]:
"""
cv2.distanceTransform(src, distanceType, maskSize)
  - src:입력영상, 바이너리 스케일
  - distanceType:거리 계산 방식 선택
    -cv2.DiST_L2, cv2.DIST_L1, cv2.DIST_L12, cv2.DIST_FAIR, cv2.DIST_WELSCH, cv2.DIST_HUBER
  - maskSize:거리 변환 커널 크기
"""

In [28]:
#거리 변환으로 전신 스켈레톤 찾기
import cv2
import numpy as np

#이미지를 읽어서 바이너리 스케일로 변환
img =cv2.imread('./img/full_body.jpg', cv2.IMREAD_GRAYSCALE)
_, biimg = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV)

#거리변환
dst = cv2.distanceTransform(biimg, cv2.DIST_L2, 5)
#거리 변환한 결과는 입력 영상의 픽셀 수가 아무리 크고 가장 먼 거리값이라
#하더라도 그 수는 작을 수 밖에 없어서 영상에 표시하면 거의 표시되지 않음
#거리값을 0-255범위로 정규화
dst = (dst/(dst.max()-dst.min()) *255).astype(np.uint8)
#거리값에 스레시홀드로 완전한 뼈대 찾기
skeleton = cv2.adaptiveThreshold(dst, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 7, -3)

#결과 출력
cv2.imshow('origin', img)
cv2.imshow('dist', dst)
cv2.imshow('skel', skeleton)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
#연결 요소 레이블링
"""
연결된 요소들끼리 분리하는 방법으로 바이너리 스케일 이미지에서 픽셀값이 0으로 끊어지지
않는 영역끼리 같은 값을 부여해서 분리하는 방법


cv2.connectedComponents(src[, labels, connectivity=8, ltype]): 연결 요소 레이블링과 개수 반환
  - src:입력 영상, 바이너리 스케일 이미지
  - labels:레이블링된 입력 영상과 같은 크기의 배열
  - connectivity:연결성을 검사할 방향 개수(4,8중 선택)
  - ltype:연결성을 검사할 방향 개수(4,8중 선택)
  - retval:레이블 개수
    
cv2.connectedComponentsWithStats(src[, labels, stats, centroids, connectivity, ltype]):레이블링과 각종 상태 정보 반환
  -stats:N x 5행렬(N:레이블 개수)
    -[x좌표, y좌표, 폭, 높이, 넓이]
  -centroids:각 레이블의 중심점 좌표, N x 2 행렬(N:레이블 개수)
"""

In [29]:
#연결된 영역 레이블링
import cv2
import numpy as np

#이미지 읽기
img = cv2.imread('./img/shapes_donut.png')
#결과 이미지 생성
img2 = np.zeros_like(img)
#그레이 스케일과 바이너리 스케일 변환
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, th = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)

#연결된 요소 레이블링 적용
cnt, labels = cv2.connectedComponents(th)  
#retval, labels, stats, cent = cv2.connectedComponentsWithStats(th)

#레이블 개수만큼 순회
for i in range(cnt):
    #레이블이 같은 영역에 랜덤한 색상 적용
    img2[labels==i] = [int(j) for j in np.random.randint(0,255,3)]
    
#결과출력
cv2.imshow('origin', img)
cv2.imshow('labeled', img2)
cv2.waitKey()
cv2.destroyAllWindows()

#stats를 이용하면 크기가 작은 레이블을 무시하는 등의 세밀한 작업도 가능

In [ ]:
#색 채우기
"""
cv2.floodFill(img, mask, seed, newVal[. loDiff, upDiff, flags])
  -img:입력영상, 1채널 혹은 3채널
  -mask:입력영상보다 2x2픽셀이 더 큰 배열, 0이 아닌 영역을 만나면 채우기 중지
  -seed:채우기 시작할 좌표
  -newVal:채우기에 사용할 색상 값
  -loDiff, upDiff:채우기 진행을 결정할 최소/최대 차이값
  -flags:채우기 방식, 선택 플래그,
    -4 또는 8 방향 채우기
    -cv2.FLODDFILL_MASK_ONLU:img가 아닌 mask에만 채우기 적용
     :채우기에 사용할 값을 8-16비트에 포함시켜야 함.
    -cv2.FLOODFILL_FIXED_RANGE:이웃 픽셀이 아닌 seed 픽셀과 비교
  -retval:채우기 한 픽셀의 개수
  -rect:채우기가 이뤄진 영역을 감싸는 사각형
  
이 함수는 img 영상의 seed 좌표에서 부터 시작해서 newVal의 값으로 채우기 시작
이 때 이웃하는 픽셀에 채우기를 계속하려면 현재 픽셀이 이웃픽셀의 loDiff를 뺀 값보다
크고 upDiff를 더한 값보다 작거나 같아야 함. 

이어서
"""

In [2]:
#마우스로 색 채우기
import cv2
import numpy as np

img = cv2.imread('./img/taekwonv1.jpg')
rows, cols = img.shape[:2]
#마스크 생성, 원래 이미지보다 2픽셀 크게
mask = np.zeros((rows+2, cols+2), np.uint8)
#채우기에 사용할 색
newVal = (255,255,255)
#최소/최대 차이 값
loDiff, upDiff = (10,10,10), (10,10,10)

#마우스 이벤트 처리 함수
def onMouse(event, x, y, flags, param):
    global mask, img
    if event == cv2.EVENT_LBUTTONDOWN:
        seed = (x,y)
        #색 채우기 적용
        retval = cv2.floodFill(img, mask, seed, newVal, loDiff, upDiff)
        #채우기 변경 결과 표시
        cv2.imshow('img', img)
        
#화면 출력
cv2.imshow('img', img)
cv2.setMouseCallback('img', onMouse)
cv2.waitKey()
cv2.destroyAllWindows()
