In [4]:
#keras 개발 process
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [12]:
(train_image, train_label), (test_image, test_label) = keras.datasets.mnist.load_data()

In [13]:
print(train_image.shape, test_image.shape)

(60000, 28, 28) (10000, 28, 28)


In [18]:

model = keras.Sequential()

model.add(keras.layers.InputLayer(28,28))

model.add(keras.layers.Flatten())

model.add(keras.layers.Dense(256, activation='relu'))
model.add(keras.layers.Dense(128, activation='relu'))

model.add(keras.layers.Dense(10, activation='softmax'))


In [49]:
model = keras.Sequential([
    keras.layers.InputLayer((28,28)),
    keras.layers.Flatten(),
    keras.layers.Dense(256, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
    ])

In [50]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_6 (Flatten)         (None, 784)               0         
                                                                 
 dense_18 (Dense)            (None, 256)               200960    
                                                                 
 dense_19 (Dense)            (None, 128)               32896     
                                                                 
 dense_20 (Dense)            (None, 10)                1290      
                                                                 
Total params: 235,146
Trainable params: 235,146
Non-trainable params: 0
_________________________________________________________________


In [51]:
model.compile(optimizer='adam',
             loss='categorical_crossentropy',
            metrics=['accuracy']
             )

In [23]:
X_train = (train_image/255.0).astype(np.float32)
X_test = (test_image/255.0).astype(np.float32)

In [29]:
(train_image[25]/255.0).astype(np.float32)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [30]:
#원핫인코딩
y_train = keras.utils.to_categorical(train_label)
y_test = keras.utils.to_categorical(test_label)

In [36]:
print(train_label[25])
print(y_train[25])

2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


In [52]:
hist = model.fit(X_train, y_train,
                epochs=10,
                batch_size=100,
                validation_split=0.3)

Epoch 1/10
420/420 [==============================] - 1s 2ms/step - loss: 0.3060 - accuracy: 0.9111 - val_loss: 0.1524 - val_accuracy: 0.9556
Epoch 2/10
420/420 [==============================] - 1s 2ms/step - loss: 0.1148 - accuracy: 0.9657 - val_loss: 0.1333 - val_accuracy: 0.9601
Epoch 3/10
420/420 [==============================] - 1s 2ms/step - loss: 0.0758 - accuracy: 0.9773 - val_loss: 0.0959 - val_accuracy: 0.9710
Epoch 4/10
420/420 [==============================] - 1s 2ms/step - loss: 0.0518 - accuracy: 0.9845 - val_loss: 0.0929 - val_accuracy: 0.9743
Epoch 5/10
420/420 [==============================] - 1s 2ms/step - loss: 0.0377 - accuracy: 0.9881 - val_loss: 0.0973 - val_accuracy: 0.9718
Epoch 6/10
420/420 [==============================] - 1s 1ms/step - loss: 0.0287 - accuracy: 0.9914 - val_loss: 0.1047 - val_accuracy: 0.9724
Epoch 7/10
420/420 [==============================] - 1s 1ms/step - loss: 0.0204 - accuracy: 0.9936 - val_loss: 0.1039 - val_accuracy: 0.9733
Epoch 

In [41]:
hist.history['accuracy']

[0.9131190180778503,
 0.9649285674095154,
 0.9768095016479492,
 0.982952356338501,
 0.9884762167930603,
 0.9906666874885559,
 0.9919523596763611,
 0.9943333268165588,
 0.9955238103866577,
 0.9964761734008789]

In [42]:
hist.history['loss']

[0.29963448643684387,
 0.11515253037214279,
 0.07641402631998062,
 0.05455218628048897,
 0.03733624517917633,
 0.02974613942205906,
 0.023671388626098633,
 0.01757560297846794,
 0.014306996949017048,
 0.011156858876347542]

In [43]:
hist.history['val_accuracy']

[0.9551110863685608,
 0.964722216129303,
 0.9711111187934875,
 0.9689444303512573,
 0.9717777967453003,
 0.968999981880188,
 0.9735000133514404,
 0.9735000133514404,
 0.9755555391311646,
 0.9756110906600952]

In [44]:
test_loss, test_acc = model.evaluate(X_test, y_test)

313/313 [==============================] - 0s 712us/step - loss: 0.0803 - accuracy: 0.9793


In [45]:
print(test_loss, test_acc)

0.08025599271059036 0.9793000221252441


In [ ]:
#새로운 데이터 추론

In [47]:
new_data = X_test[:5]
new_data

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

    

In [54]:
result = model.predict(new_data)
result

array([[8.29971157e-07, 3.76099450e-07, 8.70294286e-07, 4.25203034e-05,
        3.98187776e-12, 2.42965648e-09, 1.65163521e-12, 9.99954224e-01,
        2.37781634e-07, 9.78495450e-07],
       [4.44885231e-13, 8.78863773e-08, 9.99999881e-01, 4.48819515e-09,
        2.50123602e-17, 6.07382417e-13, 6.80933478e-12, 8.27535794e-13,
        1.57043267e-11, 4.82410279e-20],
       [3.64989887e-07, 9.99876499e-01, 1.95721768e-05, 2.86831010e-07,
        7.78241611e-06, 6.43792475e-07, 1.66756945e-06, 5.06560973e-05,
        4.21063014e-05, 4.54126337e-07],
       [9.99999166e-01, 1.33713030e-09, 8.68426895e-08, 1.77425335e-13,
        2.22923069e-10, 1.03771631e-08, 5.18072284e-07, 2.09566792e-07,
        2.82077056e-10, 3.67628807e-08],
       [1.30453248e-09, 3.51126038e-11, 3.71912813e-11, 2.21238652e-12,
        9.99997258e-01, 1.37788305e-11, 4.53317028e-09, 1.86822535e-09,
        4.62463123e-10, 2.76598780e-06]], dtype=float32)

In [56]:
#결과 확인하기
np.argmax(result, axis=1)

array([7, 2, 1, 0, 4], dtype=int64)