In [ ]:
#시험에 사용할 수 있는 패키지
#numpy, pandas, scikit-learn, xgboost

In [ ]:
https://hwiyong.tistory.com/91
https://blog.nerdfactory.ai/2021/06/15/Normalization-Theorem-1.html

In [15]:
#표준화와 정규화
import numpy as np

"""
정규화
- 데이터가 가진 feature의 스케일이 심하게 차이가 나는 경우 사용
- 데이터의 범위를 0에서 1사이로 변환

>min_max
>>> (X - MIN) / (MAX-MIN) 

표준화
-평균이 0이고 분산이 1로 변환해서 데이터 분포를 조정하는 방법

>z_score
>>> (X - 평균) / 표준편차

정칙화
-일반적으로 가중치를 조정할 때 추가적인 제약을 주는 것

"""
#정규화
#min_max
def min_max(list_n):
    mylist=[]
    for i in list_n:
        mylist.append((i-min(list_n)) /(max(list_n)-min(list_n)))
    return mylist

#max_abs
#절댓값이 가장 큰 수의 절대값으로 전체를 나누어 모든 데이터의 범위를 [-1,1]로 조절 
df = pd.DataFrame([[1.0, 18],
                  [0.8, 25],
                  [-0.5, 30],
                  [-1.8, 21],
                  [1.2, 26],
                  [0.6, 15]])
df.columns = ['sight', 'age']
df_new = df/df.abs().max()

#Robust scaler
#평균과 분산 대신에 중간값과 사분위 값 사용
#중앙값과 IQR 사용, 아웃라이어의 영향 최소화
#i - median(list_n)/IQR
scalar = RobustScalar()
scalar.fit(df)
print(scalar.transform(df))

#표준화
def z_score(list_n):
    my_list=[]
    for i in list_n:
        my_list.append((i-np.mean(list_n))/np.std(list_n))
    return my_list

#sklearn을 이용한 표준화
import sklearn
from sklearn.preprocessing import *
#StandardScaler().fit_transform(data)

#scipy를 이용한 표준화
import scipy.stats as ss 
#ss.zscore(data)

#Regularization(정칙화)
#학습 데이터에 대한 민감도를 낮춰줍니다.
#결과적으로) 과적합을 방지하기 위해 사용됩니다.
"""
-Ridge
-Lasso
-Elastic Net
-Fused Lasso
-Group Lasso
-Graph Constrained Regularization

"""



In [7]:
list_m=[10,20,30,40,50,60,70,80,90,100]
min_max(list_m)

[0.0,
 0.1111111111111111,
 0.2222222222222222,
 0.3333333333333333,
 0.4444444444444444,
 0.5555555555555556,
 0.6666666666666666,
 0.7777777777777778,
 0.8888888888888888,
 1.0]

In [10]:
list_m=[10,20,30,40,50,60,70,80,90,100]
z_score(list_m)

[-1.5666989036012806,
 -1.2185435916898848,
 -0.8703882797784892,
 -0.5222329678670935,
 -0.17407765595569785,
 0.17407765595569785,
 0.5222329678670935,
 0.8703882797784892,
 1.2185435916898848,
 1.5666989036012806]

In [16]:
data=np.random.randint(30 , size=(6,5))
data

array([[28,  2,  9,  4, 17],
       [ 3, 27, 16, 26,  3],
       [23, 20,  9, 16, 26],
       [28, 16,  7, 22, 24],
       [ 3, 10, 28, 29, 25],
       [13, 11, 12, 29,  1]])

In [18]:
#sklearn을 이용한 표준화
import sklearn
from sklearn.preprocessing import *
StandardScaler().fit_transform(data)

array([[ 1.09321633, -1.555226  , -0.63481105, -1.92487096,  0.09682458],
       [-1.2493901 ,  1.59725914,  0.35267281,  0.56613852, -1.25871959],
       [ 0.62469505,  0.7145633 , -0.63481105, -0.56613852,  0.96824584],
       [ 1.09321633,  0.21016568, -0.9169493 ,  0.1132277 ,  0.77459667],
       [-1.2493901 , -0.54643076,  2.04550229,  0.90582163,  0.87142125],
       [-0.31234752, -0.42033135, -0.21160368,  0.90582163, -1.45236875]])

In [19]:
#scipy를 이용한 표준화
import scipy.stats as ss 
ss.zscore(data)

array([[ 1.09321633, -1.555226  , -0.63481105, -1.92487096,  0.09682458],
       [-1.2493901 ,  1.59725914,  0.35267281,  0.56613852, -1.25871959],
       [ 0.62469505,  0.7145633 , -0.63481105, -0.56613852,  0.96824584],
       [ 1.09321633,  0.21016568, -0.9169493 ,  0.1132277 ,  0.77459667],
       [-1.2493901 , -0.54643076,  2.04550229,  0.90582163,  0.87142125],
       [-0.31234752, -0.42033135, -0.21160368,  0.90582163, -1.45236875]])

In [21]:
min_max(data[0])

[1.0, 0.0, 0.2692307692307692, 0.07692307692307693, 0.5769230769230769]

In [22]:
z_score(data[0])

[1.6791019206444542,
 -1.0494387004027839,
 -0.31483161012083516,
 -0.8395509603222271,
 0.5247193502013919]

In [ ]:
#total 정리
#결정트리 사용하기
import numpy as np
from sklearn.tree import DecisionTreeClassfier
tree_model = DecisionTreeClassifier(max_depth=2, random_state=3)
tree_model.fit(iris.data,iris.target)
#라벨링 되지 않은 데이터들
my_iris = np.array([[5, 3.5, 1.4, 0.25], [6.7, 3.0, 5.2, 2.2]]) 
result = tree_model.predict(my_iris)
print(result, iris.target_name[result])
#추론
tree_model.predict_proba(my_iris)
#데이터셋 분할
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(iris.data,
                                                   iris.target,
                                                   test_size=0.2,
                                                   random_state=12,
                                                   stratify = iris.target)##원본 데이터의 클래스별 비율에 맞춰 나누도록 처리

#평가
pred_train = tree_model.predict(X_train)
pred_test = tree_model.predict(X_test)
#정확도 
from sklearn.metrics import accuracy_score
#accuracy_score(정답, 예측값)

acc_train = accuracy_score(Y_train, pred_train)
acc_test = accuracy_score(Y_test, pred_test)
print('훈련데이터셋 정확도: {}, 테스트데이터셋 정확도: {}'.format(acc_train, acc_test))